# Generated by Django 4.2.7 on 2023-11-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
    ]
