# Generated by Django 4.2.7 on 2023-12-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0013_reviews_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_of_ratings',
        ),
    ]
