# Generated by Django 5.0 on 2023-12-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0015_reviews_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_user',
        ),
    ]
